### ISSUE TITLE
請重新調整測試案例內容

### ISSUE THREAD

**Issue by hatelove** [yumetokiseki/TDD_TEST#1]
不符合作業內容，請將作業上需求的描述，透過測試案例來呈現。

測試案例的描述內容，應該至少包含：

1. 那 11 筆資料 (maybe Product)
1. 幾筆一組
1. 加總哪一欄

請使用同一個方法，而不是加總一個欄位就要加開一個方法。

**Comment by yumetokiseki** [comment]
已經更新

**Comment by hatelove** [comment]
well done.

## 結論
可以參考一下我的 sample code: https://gist.github.com/hatelove/f5a4c2591293828b637f#file-getsumbypagesize_v2-cs

重點 focus 在下列幾點：

1. 呼叫端怎麼呼叫最好用, 語意清楚, 參數夠少, intellisense輔助。
2. API 在需求異動時，能越穩定越好，代表支援有足夠的彈性。在面對重構時，也不會影響到呼叫端的使用，例如 property rename。
3. 測試案例要怎麼呈現，最像口語化的描述著呼叫端使用情境。包含怎麼寫語意最清楚，寫起來最快。

這個 homework 基本上有四種方式來實作，也考驗著對 C# 的熟悉程度。

1. 使用 enum, production code 以 if/else 來分辨
1. 使用 string + reflection 來動態決定使用哪一個 property 加總
1. 使用 delegate/lambda 針對 Product 型別來處理
1. 使用 generic 支援泛型，使用 extension method 針對所有集合都提供這樣的功能
